docker_station_deploy_path: /volume1/docker/docker-station

portainer_vers: 2.33.6
registry_vers: 3

portainer_license_key: "{{ vault_portainer_license_key }}"
portainer_trusted_origins: portainer.texhome.lan

cert_name: registry

portainer_http_port: 8000
portainer_https_port: 9443
